# name: Deploy to Private Server
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install pnpm
#         run: npm install -g pnpm
#       - name: Install dependencies
#         run: pnpm install
#       - name: Install prop-types
#         run: pnpm install prop-types
#       - name: Build app
#         run: pnpm run build
#       - name: Create new directory on server
#         uses: appleboy/ssh-action@master
#         with:
#           host: 10.255.38.26:142
#           username: root
#           password: M!w6By7#6%
#           script: mkdir -p /root/web-app/ceam-frontend-new
#       - name: Copy files to new directory on server
#         uses: appleboy/scp-action@master
#         with:
#           host: 10.255.38.26:142
#           username: root
#           password: M!w6By7#6%
#           source: ./
#           target: /root/web-app/ceam-frontend-new
#       - name: Switch to new version and remove old version
#         uses: appleboy/ssh-action@master
#         with:
#           host: 10.255.38.26:142
#           username: root
#           password: M!w6By7#6%
#           script: |
#             mv /root/web-app/ceam-frontend /root/web-app/ceam-frontend-old
#             mv /root/web-app/ceam-frontend-new /root/web-app/ceam-frontend
#             rm -rf /root/web-app/ceam-frontend-old
#       - name: Restart app with PM2
#         run: pm2 restart ceam-frontend
